spring.application.name=GestionHuilerieBack

spring.datasource.url=jdbc:mysql://localhost:3306/gestionhuilerie
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.docker.compose.enabled=false

server.port=8000
app.storage.bon-pesee-dir=C:/Users/takwa/Desktop/bon pesee
