package IntegrationTests.guides;

import com.fasterxml.jackson.databind.ObjectMapper;
import dto.AuthResponseDTO;
import dto.GuideProductionCreateDTO;
import dto.GuideProductionDTO;
import dto.SignupRequestDTO;
import Models.Entreprise;
import Models.Huilerie;
import Models.Profil;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.WebApplicationContext;
import Repositories.EntrepriseRepository;
import Repositories.HuilerieRepository;
import Repositories.ProfilRepository;
import Repositories.UtilisateurRepository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = org.example.gestionhuilerieback.GestionHuilerieBackApplication.class)
@ActiveProfiles("test")
@TestPropertySource(properties = {
    "spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "spring.jpa.hibernate.ddl-auto=create-drop",
    "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect"
})
@Transactional
class GuideProductionIntegrationTest {

    @Autowired
    private WebApplicationContext webApplicationContext;

    private MockMvc mockMvc;
    private ObjectMapper objectMapper;

    private String jwtToken;

    @Autowired
    private EntrepriseRepository entrepriseRepository;

    @Autowired
    private HuilerieRepository huilerieRepository;

    @Autowired
    private ProfilRepository profilRepository;

    @Autowired
    private UtilisateurRepository utilisateurRepository;

    @BeforeEach
    void setup() {
        mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext).build();
        objectMapper = new ObjectMapper();
    }

    @BeforeEach
    void setupTestData() {
        // Créer une entreprise
        Entreprise entreprise = entrepriseRepository.findAll().stream().findFirst().orElse(null);
        if (entreprise == null) {
            entreprise = new Entreprise();
            entreprise.setNom("Entreprise Test");
            entreprise.setAdresse("Adresse Test");
            entreprise.setTelephone("0123456789");
            entreprise.setEmail("entreprise@test.com");
            entreprise = entrepriseRepository.save(entreprise);
        }

        // Créer un profil (vérifier s'il existe déjà)
        Profil profil = profilRepository.findByNom("ADMIN_TEST").orElse(null);
        if (profil == null) {
            profil = new Profil();
            profil.setNom("ADMIN_TEST");
            profil.setDescription("Profil administrateur test");
            profil = profilRepository.save(profil);
        }

        // Créer une huilerie
        Huilerie huilerie = huilerieRepository.findAll().stream().findFirst().orElse(null);
        if (huilerie == null) {
            huilerie = new Huilerie();
            huilerie.setNom("Huilerie Test");
            huilerie.setLocalisation("Test Location");
            huilerie.setType("artisanal");
            huilerie.setActive(true);
            huilerie.setEntreprise(entreprise);
            huilerie = huilerieRepository.save(huilerie);
        }
    }

    @BeforeEach
    void setupAuth() throws Exception {
        // Skip JWT auth for now - tests will use permitAll endpoints
        jwtToken = null;
    }

    @Test
    @DisplayName("createWithTemplateAutoGenerated - Création guide avec étapes auto générées")
    void createWithTemplateAutoGenerated() throws Exception {
        // Given: Données de guide valides sans étapes personnalisées
        GuideProductionCreateDTO dto = new GuideProductionCreateDTO();
        dto.setNom("Guide 3 phases");
        dto.setTypeMachine("3_phase");
        dto.setHuilerieId(1L);

        // When: Création du guide
        MvcResult result = mockMvc.perform(post("/api/guide-productions")
                .header("Authorization", "Bearer " + jwtToken)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dto)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.idGuideProduction").exists())
                .andExpect(jsonPath("$.nom").value("Guide 3 phases"))
                .andExpect(jsonPath("$.etapes").isArray())
                .andReturn();

        // Then: Vérifier que les étapes ont été générées automatiquement
        String response = result.getResponse().getContentAsString();
        GuideProductionDTO guideDto = objectMapper.readValue(response, GuideProductionDTO.class);
        
        assertThat(guideDto.getIdGuideProduction()).isNotNull();
        assertThat(guideDto.getNom()).isEqualTo("Guide 3 phases");
        assertThat(guideDto.getEtapes()).isNotEmpty();
        assertThat(guideDto.getEtapes().get(0).getCodeEtape()).isNotEmpty();
    }

    @Test
    @DisplayName("findAllSuccess - Liste des guides de production")
    void findAllSuccess() throws Exception {
        // Given: Créer un guide
        GuideProductionCreateDTO dto = new GuideProductionCreateDTO();
        dto.setNom("Guide 3 phases");
        dto.setTypeMachine("3_phase");
        dto.setHuilerieId(1L);

        mockMvc.perform(post("/api/guide-productions")
                .header("Authorization", "Bearer " + jwtToken)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dto)))
                .andExpect(status().isCreated());

        // When: Récupérer la liste des guides
        mockMvc.perform(get("/api/guide-productions")
                .header("Authorization", "Bearer " + jwtToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$[0].nom").value("Guide 3 phases"));
    }

    @Test
    @DisplayName("findByIdSuccess - Récupération d'un guide par ID")
    void findByIdSuccess() throws Exception {
        // Given: Créer un guide
        GuideProductionCreateDTO dto = new GuideProductionCreateDTO();
        dto.setNom("Guide 3 phases");
        dto.setTypeMachine("3_phase");
        dto.setHuilerieId(1L);

        MvcResult createResult = mockMvc.perform(post("/api/guide-productions")
                .header("Authorization", "Bearer " + jwtToken)
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(dto)))
                .andExpect(status().isCreated())
                .andReturn();

        GuideProductionDTO createdGuide = objectMapper.readValue(
            createResult.getResponse().getContentAsString(), 
            GuideProductionDTO.class
        );

        // When: Récupérer le guide par ID
        mockMvc.perform(get("/api/guide-productions/" + createdGuide.getIdGuideProduction())
                .header("Authorization", "Bearer " + jwtToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.idGuideProduction").value(createdGuide.getIdGuideProduction()))
                .andExpect(jsonPath("$.nom").value("Guide 3 phases"));
    }
}
